# Generated by Django 4.0.3 on 2023-08-10 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universityapp', '0002_alter_universitypostimages_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Universities',
            new_name='University',
        ),
        migrations.AlterField(
            model_name='universitypostimages',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_post_images', to='universityapp.universityposts'),
        ),
    ]
