# Generated by Django 4.0.3 on 2023-08-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0004_rename_universityfollowers_universityfollower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
