# Generated by Django 4.0.3 on 2023-08-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0005_university_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityreview',
            name='edit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='universityreview',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
    ]
