version: '3.9'

services:
  socialmediaapi:
    build: .
    command: python SocialMediaApi/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A SocialMediaApi  worker -l info --pool=solo

    volumes:
      - .:/app
    depends_on:
      - socialmediaapi
      - redis

  celery-beat:
    build: .
    command: celery -A SocialMediaApp beat -l info
    volumes:
      - .:/app
    depends_on:
      - socialmediaapi
      - redis

