version: '3.9'

services:
  socialmediaapi:
    build: .
    command: /startdjango
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: /startceleryworker

    volumes:
      - .:/app
    depends_on:
      - socialmediaapi
      - redis

  celery-beat:
    build: .
    command: /startcelerybeat
    volumes:
      - .:/app
    depends_on:
      - socialmediaapi
      - redis

