# Generated by Django 4.0.3 on 2024-04-20 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('email_domain', models.CharField(max_length=50)),
                ('university_profile', models.ImageField(default='default.jpg', upload_to='universities_pic')),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=110, null=True)),
                ('text', models.TextField(blank=True)),
                ('upload_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='university_post_images')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('review', models.TextField(max_length=500)),
                ('reply', models.CharField(max_length=500)),
                ('upload_date', models.DateField(auto_now=True)),
                ('edit_date', models.DateField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universityapp.university')),
            ],
        ),
    ]
